Create UpdateTenantCommonVariable.ps1
OctopusDeploy/OctopusDeploy-Api pull request #173
Opened 2023-09-18 22:27 UTC by briggs-octo

2023-09-18 22:32 UTC, briggs-octo commented
PowerShell script for updating a common variable on a tenant.

2023-09-28 13:57 UTC, SeanStanway-Octopus requested changes
Alter 
`foreach ($templateVariable in $libraryVariableSets.$librarySetId.Variables) { 
    $templateVariable.$variableValueId = $newValue 
}`
to
`$libraryVariableSets.$librarySetId.Variables.$variableValueId = $newValue`
for simplicity

2023-09-28 18:29 UTC, briggs-octo reviewed
Updated

2023-09-29 08:34 UTC, SeanStanway-Octopus approved these changes

2023-09-29 08:35 UTC, merged